language : python
python:
    - "3.8"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose

env:
  global:
    - DB_NAME=trade_core
    - DB_PASSWORD=test123

before_script:
  - psql -c 'create database trade_core_test;' -U postgres
  - psql -c "create user mmosoroohh with password 'test123';" -U mmosoroohh

script:
- nosetests --with-coverage --cover-package=app
- pytest

after_script:
   - coveralls