# Generated by Django 3.2 on 2023-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
